// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaxCounterWeb.Data.PaxCounterWeb.Data;

#nullable disable

namespace PaxCounterWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("PaxCounterWeb.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceUid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("PaxCounterWeb.Models.PaxCounterWeb.Models.RssiSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaxSampleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rssi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PaxSampleId");

                    b.ToTable("RssiSamples");
                });

            modelBuilder.Entity("PaxCounterWeb.Models.PaxSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RssiLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("WifiCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("PaxSamples");
                });

            modelBuilder.Entity("PaxCounterWeb.Models.PaxCounterWeb.Models.RssiSample", b =>
                {
                    b.HasOne("PaxCounterWeb.Models.PaxSample", "PaxSample")
                        .WithMany("RssiSamples")
                        .HasForeignKey("PaxSampleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaxSample");
                });

            modelBuilder.Entity("PaxCounterWeb.Models.PaxSample", b =>
                {
                    b.HasOne("PaxCounterWeb.Models.Device", "Device")
                        .WithMany("PaxSamples")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("PaxCounterWeb.Models.Device", b =>
                {
                    b.Navigation("PaxSamples");
                });

            modelBuilder.Entity("PaxCounterWeb.Models.PaxSample", b =>
                {
                    b.Navigation("RssiSamples");
                });
#pragma warning restore 612, 618
        }
    }
}
